Test: Ajustado teste ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -37,6 +37,7 @@ jobs:
           POSTGRES_USER: ${{ secrets.ZNY_POSTGRES_USER }}
           POSTGRES_PASSWORD: ${{ secrets.ZNY_POSTGRES_PASSWORD }}
           POSTGRES_DB: ${{ secrets.ZNY_POSTGRES_DB }}
+          DATABASE_URL: ${{ secrets.ZNY_DATABASE_URL }}
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
@@ -66,6 +67,11 @@ jobs:
 
           if [ -z "$DOCKER_PASSWORD" ]; then
             echo "Error: DOCKER_PASSWORD is not set!"
+            exit 1
+          fi
+
+          if [ -z "$DATABASE_URL" ]; then
+            echo "Error: DATABASE_URL is not set!"
             exit 1
           fi
 
