Test: Ajuste para ci Dockerfile

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,19 +1,3 @@
-name: CI/CD Zenny
-
-on:
-  push:
-    branches:
-      - "feature/**"
-      - "dev"
-      - "hml"
-      - "main"
-  pull_request:
-    branches:
-      - "dev"
-      - "hml"
-      - "main"
-  workflow_dispatch:
-
 jobs:
   build-test:
     runs-on: ubuntu-latest
@@ -33,55 +17,31 @@ jobs:
         run: docker --version && docker compose version
 
       - name: Create temp env file for Postgres
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-          POSTGRES_USER: ${{ secrets.ZNY_POSTGRES_USER }}
-          POSTGRES_PASSWORD: ${{ secrets.ZNY_POSTGRES_PASSWORD }}
-          POSTGRES_DB: ${{ secrets.ZNY_POSTGRES_DB }}
         run: |
-          echo "POSTGRES_USER=$POSTGRES_USER" > .env.ci
-          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env.ci
-          echo "POSTGRES_DB=$POSTGRES_DB" >> .env.ci
-          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> .env.ci
-          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> .env.ci
+          #! /bin/bash
+          set -e
+
+          # Lista de variáveis obrigatórias
+          REQUIRED_VARS=("ZNY_POSTGRES_USER" "ZNY_POSTGRES_PASSWORD" "ZNY_POSTGRES_DB" "DOCKER_USERNAME" "DOCKER_PASSWORD")
+
+          # Checa se cada variável está definida
+          for VAR_NAME in "${REQUIRED_VARS[@]}"; do
+            VALUE="${{ secrets[$VAR_NAME] }}"
+            if [ -z "$VALUE" ]; then
+              echo "Error: secret $VAR_NAME is not set!"
+              exit 1
+            fi
+          done
+
+          # Cria o .env.ci
+          echo "POSTGRES_USER=${{ secrets.ZNY_POSTGRES_USER }}" > .env.ci
+          echo "POSTGRES_PASSWORD=${{ secrets.ZNY_POSTGRES_PASSWORD }}" >> .env.ci
+          echo "POSTGRES_DB=${{ secrets.ZNY_POSTGRES_DB }}" >> .env.ci
+          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env.ci
+          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env.ci
 
       - name: Print .env.ci for debugging
         run: cat .env.ci
 
       - name: Run tests with docker compose
         run: docker compose --env-file .env.ci -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from api
-
-  docker-build-push:
-    runs-on: ubuntu-latest
-    needs: build-test
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Set Docker image tag
-        id: tag
-        run: |
-          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
-          if [[ "$BRANCH_NAME" == "main" ]]; then
-            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
-          elif [[ "$BRANCH_NAME" == "dev" ]]; then
-            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
-          elif [[ "$BRANCH_NAME" == "hml" ]]; then
-            echo "IMAGE_TAG=hml" >> $GITHUB_ENV
-          else
-            echo "IMAGE_TAG=feature-${BRANCH_NAME}" >> $GITHUB_ENV
-
-      - name: Build Docker image
-        run: |
-          docker build -t clebernandi/carteira-zen-backend:${{ env.IMAGE_TAG }} --target final .
-
-      - name: Push Docker image
-        run: |
-          docker push clebernandi/carteira-zen-backend:${{ env.IMAGE_TAG }}
